package com.sanicorporation.worldnews.core.domain

enum class Countries(val code: String, val imageUrl: String) {
    Emirates("ae", "https://upload.wikimedia.org/wikipedia/commons/c/cb/Flag_of_the_United_Arab_Emirates.svg"),
    Argentina("ar", "https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg"),
    Austria("at","https://upload.wikimedia.org/wikipedia/commons/4/41/Flag_of_Austria.svg"),
    Australia("au", "https://upload.wikimedia.org/wikipedia/commons/8/88/Flag_of_Australia_%28converted%29.svg"),
    Belgium("be","https://upload.wikimedia.org/wikipedia/commons/6/65/Flag_of_Belgium.svg"),
    Bulgary("bg", "https://upload.wikimedia.org/wikipedia/commons/9/9a/Flag_of_Bulgaria.svg"),
    Brazil("br","https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Brazil.svg"),
    Canada("ca","https://upload.wikimedia.org/wikipedia/commons/d/d9/Flag_of_Canada_%28Pantone%29.svg"),
    Switzerland("ch","https://upload.wikimedia.org/wikipedia/commons/0/08/Flag_of_Switzerland_%28Pantone%29.svg"),
    China("cn","https://upload.wikimedia.org/wikipedia/commons/f/fa/Flag_of_the_People%27s_Republic_of_China.svg"),
    Colombia("co","https://upload.wikimedia.org/wikipedia/commons/2/21/Flag_of_Colombia.svg"),
    Cuba("cu","https://upload.wikimedia.org/wikipedia/commons/b/bd/Flag_of_Cuba.svg"),
    CzechRepublic("cz","https://upload.wikimedia.org/wikipedia/commons/c/cb/Flag_of_the_Czech_Republic.svg"),
    Deutchland("de","https://upload.wikimedia.org/wikipedia/commons/b/ba/Flag_of_Germany.svg"),
    Egypt("eg","https://upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_Egypt.svg"),
    France("fr", "https://upload.wikimedia.org/wikipedia/commons/c/c3/Flag_of_France.svg"),
    UnitedKingdom("gb","https://upload.wikimedia.org/wikipedia/commons/a/ae/Flag_of_the_United_Kingdom.svg"),
    Greece("gr","https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Greece.svg"),
    HongKong("hk","https://upload.wikimedia.org/wikipedia/commons/5/5b/Flag_of_Hong_Kong.svg"),
    Hungrary("hu","https://upload.wikimedia.org/wikipedia/commons/c/c1/Flag_of_Hungary.svg"),
    Indonesia("id","https://upload.wikimedia.org/wikipedia/commons/9/9f/Flag_of_Indonesia.svg"),
    Ireland("ie","https://upload.wikimedia.org/wikipedia/commons/4/45/Flag_of_Ireland.svg"),
    Israel("il","https://upload.wikimedia.org/wikipedia/commons/d/d4/Flag_of_Israel.svg"),
    India("in","https://upload.wikimedia.org/wikipedia/commons/4/41/Flag_of_India.svg"),
    Italy("it","https://upload.wikimedia.org/wikipedia/commons/0/03/Flag_of_Italy.svg"),
    Japan("jp","https://upload.wikimedia.org/wikipedia/commons/9/9e/Flag_of_Japan.svg"),
    SouthKorea("kr","https://upload.wikimedia.org/wikipedia/commons/0/09/Flag_of_South_Korea.svg"),
    Lithuania("lt","https://upload.wikimedia.org/wikipedia/commons/1/11/Flag_of_Lithuania.svg"),
    Latvia("lv","https://upload.wikimedia.org/wikipedia/commons/8/84/Flag_of_Latvia.svg"),
    Morocco("ma","https://upload.wikimedia.org/wikipedia/commons/2/2c/Flag_of_Morocco.svg"),
    Mexico("mx","https://upload.wikimedia.org/wikipedia/commons/f/fc/Flag_of_Mexico.svg"),
    Malaysia("my","https://upload.wikimedia.org/wikipedia/commons/6/66/Flag_of_Malaysia.svg"),
    Nigeria("ng","https://upload.wikimedia.org/wikipedia/commons/7/79/Flag_of_Nigeria.svg"),
    Netherlands("nl","https://upload.wikimedia.org/wikipedia/commons/2/20/Flag_of_the_Netherlands.svg"),
    Norway("no","https://upload.wikimedia.org/wikipedia/commons/d/d9/Flag_of_Norway.svg"),
    NewZealand("nz","https://upload.wikimedia.org/wikipedia/commons/3/3e/Flag_of_New_Zealand.svg"),
    Philippines("ph","https://upload.wikimedia.org/wikipedia/commons/9/99/Flag_of_the_Philippines.svg"),
    Poland("pl","https://upload.wikimedia.org/wikipedia/commons/1/12/Flag_of_Poland.svg"),
    Portugal("pt","https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Portugal.svg"),
    Romania("ro","https://upload.wikimedia.org/wikipedia/commons/7/73/Flag_of_Romania.svg"),
    Serbia("rs","https://upload.wikimedia.org/wikipedia/commons/f/ff/Flag_of_Serbia.svg"),
    Russia("ru","https://upload.wikimedia.org/wikipedia/commons/f/f3/Flag_of_Russia.svg"),
    SaudiArabia("sa","https://upload.wikimedia.org/wikipedia/commons/0/0d/Flag_of_Saudi_Arabia.svg"),
    Sweden("se","https://upload.wikimedia.org/wikipedia/commons/4/4c/Flag_of_Sweden.svg"),
    Singapore("sg","https://upload.wikimedia.org/wikipedia/commons/4/48/Flag_of_Singapore.svg"),
    Slovenia("si","https://upload.wikimedia.org/wikipedia/commons/f/f0/Flag_of_Slovenia.svg"),
    Slovakia("sk","https://upload.wikimedia.org/wikipedia/commons/e/e6/Flag_of_Slovakia.svg"),
    Thailand("th","https://upload.wikimedia.org/wikipedia/commons/a/a9/Flag_of_Thailand.svg"),
    Turkey("tr","https://upload.wikimedia.org/wikipedia/commons/b/b4/Flag_of_Turkey.svg"),
    Taiwan("tw","https://upload.wikimedia.org/wikipedia/commons/7/72/Flag_of_the_Republic_of_China.svg"),
    Ukraine("ua","https://upload.wikimedia.org/wikipedia/commons/4/49/Flag_of_Ukraine.svg"),
    UnitedStates("us","https://upload.wikimedia.org/wikipedia/commons/a/a4/Flag_of_the_United_States.svg"),
    Venezuela("ve","https://upload.wikimedia.org/wikipedia/commons/0/06/Flag_of_Venezuela.svg"),
    SouthAfrica("za","https://upload.wikimedia.org/wikipedia/commons/a/af/Flag_of_South_Africa.svg")
}